<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\APP.Domain\APP.Domain.csproj" />
    <ProjectReference Include="..\App.Repositories\App.Repositories.csproj" />
  </ItemGroup>

</Project>
